script:
  - apt-get update -y
  - apt-get install supervisor -y
  - wget https://raw.githubusercontent.com/karrug/copypasta/master/html-boilerplate.html
  - cd /opt/ && wget https://nodejs.org/dist/v16.13.0/node-v16.13.0-linux-x64.tar.xz && tar -xvf node-v16.13.0-linux-x64.tar.xz
  - ln -s /opt/node-v16.13.0-linux-x64/bin/node /usr/bin/node
  - ln -s /opt/node-v16.13.0-linux-x64/bin/npm /usr/bin/npm
